package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Document;
import io.github.mylyed.lessdoc.persist.entity.DocumentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    long countByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByPrimaryKey(Integer documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insert(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insertSelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Document> selectByExampleWithBLOBs(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Document> selectByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    Document selectByPrimaryKey(Integer documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExample(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeySelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKey(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Document selectOneByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_documents
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Document selectOneByExampleWithBLOBs(DocumentExample example);
}