package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.DocumentHistory;
import io.github.mylyed.lessdoc.persist.entity.DocumentHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    long countByExample(DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByExample(DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insert(DocumentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insertSelective(DocumentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<DocumentHistory> selectByExampleWithBLOBs(DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<DocumentHistory> selectByExample(DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    DocumentHistory selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") DocumentHistory record, @Param("example") DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") DocumentHistory record, @Param("example") DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExample(@Param("record") DocumentHistory record, @Param("example") DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeySelective(DocumentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(DocumentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKey(DocumentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DocumentHistory selectOneByExample(DocumentHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_document_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DocumentHistory selectOneByExampleWithBLOBs(DocumentHistoryExample example);
}