package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Itemset;
import io.github.mylyed.lessdoc.persist.entity.ItemsetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    long countByExample(ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByExample(ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insert(Itemset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insertSelective(Itemset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<Itemset> selectByExampleWithBLOBs(ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<Itemset> selectByExample(ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    Itemset selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Itemset record, @Param("example") ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Itemset record, @Param("example") ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExample(@Param("record") Itemset record, @Param("example") ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeySelective(Itemset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Itemset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKey(Itemset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Itemset selectOneByExample(ItemsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_itemsets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Itemset selectOneByExampleWithBLOBs(ItemsetExample example);
}