package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Label;
import io.github.mylyed.lessdoc.persist.entity.LabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    long countByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    List<Label> selectByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    Label selectByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExample(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKey(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_label
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Label selectOneByExample(LabelExample example);
}