package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Member;
import io.github.mylyed.lessdoc.persist.entity.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    Member selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKey(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_members
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Member selectOneByExample(MemberExample example);
}