package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Migration;
import io.github.mylyed.lessdoc.persist.entity.MigrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MigrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    long countByExample(MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByExample(MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByPrimaryKey(Integer migrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insert(Migration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insertSelective(Migration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Migration> selectByExampleWithBLOBs(MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Migration> selectByExample(MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    Migration selectByPrimaryKey(Integer migrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") Migration record, @Param("example") MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Migration record, @Param("example") MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExample(@Param("record") Migration record, @Param("example") MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeySelective(Migration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Migration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKey(Migration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Migration selectOneByExample(MigrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_migrations
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Migration selectOneByExampleWithBLOBs(MigrationExample example);
}