package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Option;
import io.github.mylyed.lessdoc.persist.entity.OptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    long countByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insert(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insertSelective(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Option> selectByExampleWithBLOBs(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<Option> selectByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    Option selectByPrimaryKey(Integer optionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExample(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeySelective(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKey(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Option selectOneByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_options
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Option selectOneByExampleWithBLOBs(OptionExample example);
}