package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Relationship;
import io.github.mylyed.lessdoc.persist.entity.RelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    long countByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByPrimaryKey(Integer relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insert(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insertSelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<Relationship> selectByExample(RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    Relationship selectByPrimaryKey(Integer relationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExample(@Param("record") Relationship record, @Param("example") RelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeySelective(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKey(Relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_relationship
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Relationship selectOneByExample(RelationshipExample example);
}