package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.TeamRelationship;
import io.github.mylyed.lessdoc.persist.entity.TeamRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    long countByExample(TeamRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByExample(TeamRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int deleteByPrimaryKey(Integer teamRelationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insert(TeamRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int insertSelective(TeamRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    List<TeamRelationship> selectByExample(TeamRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    TeamRelationship selectByPrimaryKey(Integer teamRelationshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") TeamRelationship record, @Param("example") TeamRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByExample(@Param("record") TeamRelationship record, @Param("example") TeamRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKeySelective(TeamRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    int updateByPrimaryKey(TeamRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_team_relationship
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TeamRelationship selectOneByExample(TeamRelationshipExample example);
}