package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Team;
import io.github.mylyed.lessdoc.persist.entity.TeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    long countByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int deleteByPrimaryKey(Integer teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int insertSelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    List<Team> selectByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    Team selectByPrimaryKey(Integer teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByExample(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKeySelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    int updateByPrimaryKey(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_teams
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Team selectOneByExample(TeamExample example);
}