package io.github.mylyed.lessdoc.persist.mapper;

import io.github.mylyed.lessdoc.persist.entity.Template;
import io.github.mylyed.lessdoc.persist.entity.TemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    long countByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<Template> selectByExampleWithBLOBs(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    List<Template> selectByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    Template selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByExample(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    int updateByPrimaryKey(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Template selectOneByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table md_templates
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Template selectOneByExampleWithBLOBs(TemplateExample example);
}