package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Attachment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.attachment_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer attachmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.book_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.document_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.file_name
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.file_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.file_size
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Double fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.http_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private String httpPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.file_ext
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private String fileExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.create_time
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_attachment.create_at
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_attachment
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.attachment_id
     *
     * @return the value of md_attachment.attachment_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.attachment_id
     *
     * @param attachmentId the value for md_attachment.attachment_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.book_id
     *
     * @return the value of md_attachment.book_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.book_id
     *
     * @param bookId the value for md_attachment.book_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.document_id
     *
     * @return the value of md_attachment.document_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.document_id
     *
     * @param documentId the value for md_attachment.document_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.file_name
     *
     * @return the value of md_attachment.file_name
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.file_name
     *
     * @param fileName the value for md_attachment.file_name
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.file_path
     *
     * @return the value of md_attachment.file_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.file_path
     *
     * @param filePath the value for md_attachment.file_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.file_size
     *
     * @return the value of md_attachment.file_size
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.file_size
     *
     * @param fileSize the value for md_attachment.file_size
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.http_path
     *
     * @return the value of md_attachment.http_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public String getHttpPath() {
        return httpPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.http_path
     *
     * @param httpPath the value for md_attachment.http_path
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setHttpPath(String httpPath) {
        this.httpPath = httpPath == null ? null : httpPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.file_ext
     *
     * @return the value of md_attachment.file_ext
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.file_ext
     *
     * @param fileExt the value for md_attachment.file_ext
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt == null ? null : fileExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.create_time
     *
     * @return the value of md_attachment.create_time
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.create_time
     *
     * @param createTime the value for md_attachment.create_time
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_attachment.create_at
     *
     * @return the value of md_attachment.create_at
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_attachment.create_at
     *
     * @param createAt the value for md_attachment.create_at
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }
}