package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Book implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.book_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.item_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.auto_release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Boolean autoRelease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.is_download
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer isDownload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.order_index
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer orderIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.description
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.publisher
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.label
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.privately_owned
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Boolean privatelyOwned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.private_token
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String privateToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.book_password
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String bookPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.editor
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String editor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.doc_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer docCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.comment_status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String commentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.comment_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.cover
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.theme
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.history_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer historyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.is_enable_share
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer isEnableShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.is_use_first_document
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Boolean useFirstDocument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_books.auto_save
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer autoSave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_books
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.book_id
     *
     * @return the value of md_books.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.book_id
     *
     * @param bookId the value for md_books.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.book_name
     *
     * @return the value of md_books.book_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.book_name
     *
     * @param bookName the value for md_books.book_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.item_id
     *
     * @return the value of md_books.item_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.item_id
     *
     * @param itemId the value for md_books.item_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.identify
     *
     * @return the value of md_books.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.identify
     *
     * @param identify the value for md_books.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.auto_release
     *
     * @return the value of md_books.auto_release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Boolean getAutoRelease() {
        return autoRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.auto_release
     *
     * @param autoRelease the value for md_books.auto_release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setAutoRelease(Boolean autoRelease) {
        this.autoRelease = autoRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.is_download
     *
     * @return the value of md_books.is_download
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getIsDownload() {
        return isDownload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.is_download
     *
     * @param isDownload the value for md_books.is_download
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIsDownload(Integer isDownload) {
        this.isDownload = isDownload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.order_index
     *
     * @return the value of md_books.order_index
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.order_index
     *
     * @param orderIndex the value for md_books.order_index
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.description
     *
     * @return the value of md_books.description
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.description
     *
     * @param description the value for md_books.description
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.publisher
     *
     * @return the value of md_books.publisher
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.publisher
     *
     * @param publisher the value for md_books.publisher
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.label
     *
     * @return the value of md_books.label
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.label
     *
     * @param label the value for md_books.label
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.privately_owned
     *
     * @return the value of md_books.privately_owned
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Boolean getPrivatelyOwned() {
        return privatelyOwned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.privately_owned
     *
     * @param privatelyOwned the value for md_books.privately_owned
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setPrivatelyOwned(Boolean privatelyOwned) {
        this.privatelyOwned = privatelyOwned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.private_token
     *
     * @return the value of md_books.private_token
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getPrivateToken() {
        return privateToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.private_token
     *
     * @param privateToken the value for md_books.private_token
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setPrivateToken(String privateToken) {
        this.privateToken = privateToken == null ? null : privateToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.book_password
     *
     * @return the value of md_books.book_password
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getBookPassword() {
        return bookPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.book_password
     *
     * @param bookPassword the value for md_books.book_password
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setBookPassword(String bookPassword) {
        this.bookPassword = bookPassword == null ? null : bookPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.status
     *
     * @return the value of md_books.status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.status
     *
     * @param status the value for md_books.status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.editor
     *
     * @return the value of md_books.editor
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.editor
     *
     * @param editor the value for md_books.editor
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.doc_count
     *
     * @return the value of md_books.doc_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getDocCount() {
        return docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.doc_count
     *
     * @param docCount the value for md_books.doc_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDocCount(Integer docCount) {
        this.docCount = docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.comment_status
     *
     * @return the value of md_books.comment_status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.comment_status
     *
     * @param commentStatus the value for md_books.comment_status
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus == null ? null : commentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.comment_count
     *
     * @return the value of md_books.comment_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.comment_count
     *
     * @param commentCount the value for md_books.comment_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.cover
     *
     * @return the value of md_books.cover
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.cover
     *
     * @param cover the value for md_books.cover
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.theme
     *
     * @return the value of md_books.theme
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.theme
     *
     * @param theme the value for md_books.theme
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.create_time
     *
     * @return the value of md_books.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.create_time
     *
     * @param createTime the value for md_books.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.history_count
     *
     * @return the value of md_books.history_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getHistoryCount() {
        return historyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.history_count
     *
     * @param historyCount the value for md_books.history_count
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setHistoryCount(Integer historyCount) {
        this.historyCount = historyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.is_enable_share
     *
     * @return the value of md_books.is_enable_share
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getIsEnableShare() {
        return isEnableShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.is_enable_share
     *
     * @param isEnableShare the value for md_books.is_enable_share
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIsEnableShare(Integer isEnableShare) {
        this.isEnableShare = isEnableShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.member_id
     *
     * @return the value of md_books.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.member_id
     *
     * @param memberId the value for md_books.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.modify_time
     *
     * @return the value of md_books.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.modify_time
     *
     * @param modifyTime the value for md_books.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.version
     *
     * @return the value of md_books.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.version
     *
     * @param version the value for md_books.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.is_use_first_document
     *
     * @return the value of md_books.is_use_first_document
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Boolean getUseFirstDocument() {
        return useFirstDocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.is_use_first_document
     *
     * @param useFirstDocument the value for md_books.is_use_first_document
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setUseFirstDocument(Boolean useFirstDocument) {
        this.useFirstDocument = useFirstDocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_books.auto_save
     *
     * @return the value of md_books.auto_save
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getAutoSave() {
        return autoSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_books.auto_save
     *
     * @param autoSave the value for md_books.auto_save
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setAutoSave(Integer autoSave) {
        this.autoSave = autoSave;
    }
}