package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class DocumentHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.history_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer historyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.action
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.action_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String actionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String documentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer modifyAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Boolean isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String markdown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_document_history.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_document_history
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.history_id
     *
     * @return the value of md_document_history.history_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.history_id
     *
     * @param historyId the value for md_document_history.history_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.action
     *
     * @return the value of md_document_history.action
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.action
     *
     * @param action the value for md_document_history.action
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.action_name
     *
     * @return the value of md_document_history.action_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.action_name
     *
     * @param actionName the value for md_document_history.action_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.document_id
     *
     * @return the value of md_document_history.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.document_id
     *
     * @param documentId the value for md_document_history.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.document_name
     *
     * @return the value of md_document_history.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.document_name
     *
     * @param documentName the value for md_document_history.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName == null ? null : documentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.parent_id
     *
     * @return the value of md_document_history.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.parent_id
     *
     * @param parentId the value for md_document_history.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.member_id
     *
     * @return the value of md_document_history.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.member_id
     *
     * @param memberId the value for md_document_history.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.modify_time
     *
     * @return the value of md_document_history.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.modify_time
     *
     * @param modifyTime the value for md_document_history.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.modify_at
     *
     * @return the value of md_document_history.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getModifyAt() {
        return modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.modify_at
     *
     * @param modifyAt the value for md_document_history.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setModifyAt(Integer modifyAt) {
        this.modifyAt = modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.version
     *
     * @return the value of md_document_history.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.version
     *
     * @param version the value for md_document_history.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.is_open
     *
     * @return the value of md_document_history.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Boolean getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.is_open
     *
     * @param isOpen the value for md_document_history.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIsOpen(Boolean isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.markdown
     *
     * @return the value of md_document_history.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getMarkdown() {
        return markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.markdown
     *
     * @param markdown the value for md_document_history.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setMarkdown(String markdown) {
        this.markdown = markdown == null ? null : markdown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_document_history.content
     *
     * @return the value of md_document_history.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_document_history.content
     *
     * @param content the value for md_document_history.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}