package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Document implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String documentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.order_sort
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer orderSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Integer modifyAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private Boolean isOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String markdown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String release;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_documents.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_documents
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.document_id
     *
     * @return the value of md_documents.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.document_id
     *
     * @param documentId the value for md_documents.document_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.document_name
     *
     * @return the value of md_documents.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.document_name
     *
     * @param documentName the value for md_documents.document_name
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName == null ? null : documentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.identify
     *
     * @return the value of md_documents.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.identify
     *
     * @param identify the value for md_documents.identify
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.book_id
     *
     * @return the value of md_documents.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.book_id
     *
     * @param bookId the value for md_documents.book_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.parent_id
     *
     * @return the value of md_documents.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.parent_id
     *
     * @param parentId the value for md_documents.parent_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.order_sort
     *
     * @return the value of md_documents.order_sort
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getOrderSort() {
        return orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.order_sort
     *
     * @param orderSort the value for md_documents.order_sort
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setOrderSort(Integer orderSort) {
        this.orderSort = orderSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.create_time
     *
     * @return the value of md_documents.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.create_time
     *
     * @param createTime the value for md_documents.create_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.member_id
     *
     * @return the value of md_documents.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.member_id
     *
     * @param memberId the value for md_documents.member_id
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.modify_time
     *
     * @return the value of md_documents.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.modify_time
     *
     * @param modifyTime the value for md_documents.modify_time
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.modify_at
     *
     * @return the value of md_documents.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Integer getModifyAt() {
        return modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.modify_at
     *
     * @param modifyAt the value for md_documents.modify_at
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setModifyAt(Integer modifyAt) {
        this.modifyAt = modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.version
     *
     * @return the value of md_documents.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.version
     *
     * @param version the value for md_documents.version
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.is_open
     *
     * @return the value of md_documents.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public Boolean getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.is_open
     *
     * @param isOpen the value for md_documents.is_open
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setIsOpen(Boolean isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.markdown
     *
     * @return the value of md_documents.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getMarkdown() {
        return markdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.markdown
     *
     * @param markdown the value for md_documents.markdown
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setMarkdown(String markdown) {
        this.markdown = markdown == null ? null : markdown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.release
     *
     * @return the value of md_documents.release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getRelease() {
        return release;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.release
     *
     * @param release the value for md_documents.release
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setRelease(String release) {
        this.release = release == null ? null : release.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_documents.content
     *
     * @return the value of md_documents.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_documents.content
     *
     * @param content the value for md_documents.content
     *
     * @mbg.generated Wed May 22 22:45:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}