package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Migration implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.migration_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer migrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.status
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_migrations.statements
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private String statements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_migrations
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.migration_id
     *
     * @return the value of md_migrations.migration_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getMigrationId() {
        return migrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.migration_id
     *
     * @param migrationId the value for md_migrations.migration_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setMigrationId(Integer migrationId) {
        this.migrationId = migrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.name
     *
     * @return the value of md_migrations.name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.name
     *
     * @param name the value for md_migrations.name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.status
     *
     * @return the value of md_migrations.status
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.status
     *
     * @param status the value for md_migrations.status
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.create_time
     *
     * @return the value of md_migrations.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.create_time
     *
     * @param createTime the value for md_migrations.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.version
     *
     * @return the value of md_migrations.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.version
     *
     * @param version the value for md_migrations.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_migrations.statements
     *
     * @return the value of md_migrations.statements
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public String getStatements() {
        return statements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_migrations.statements
     *
     * @param statements the value for md_migrations.statements
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setStatements(String statements) {
        this.statements = statements == null ? null : statements.trim();
    }
}