package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;

public class TeamMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_team_member.team_member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer teamMemberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_team_member.team_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_team_member.member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_team_member.role_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_team_member
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_team_member.team_member_id
     *
     * @return the value of md_team_member.team_member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getTeamMemberId() {
        return teamMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_team_member.team_member_id
     *
     * @param teamMemberId the value for md_team_member.team_member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setTeamMemberId(Integer teamMemberId) {
        this.teamMemberId = teamMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_team_member.team_id
     *
     * @return the value of md_team_member.team_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_team_member.team_id
     *
     * @param teamId the value for md_team_member.team_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_team_member.member_id
     *
     * @return the value of md_team_member.member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_team_member.member_id
     *
     * @param memberId the value for md_team_member.member_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_team_member.role_id
     *
     * @return the value of md_team_member.role_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_team_member.role_id
     *
     * @param roleId the value for md_team_member.role_id
     *
     * @mbg.generated Fri May 10 23:30:51 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}