package io.github.mylyed.lessdoc.persist.entity;

import java.io.Serializable;
import java.util.Date;

public class Template implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.template_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.template_name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.member_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.book_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.is_global
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer isGlobal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.modify_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.modify_at
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Integer modifyAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column md_templates.template_content
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table md_templates
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.template_id
     *
     * @return the value of md_templates.template_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.template_id
     *
     * @param templateId the value for md_templates.template_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.template_name
     *
     * @return the value of md_templates.template_name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.template_name
     *
     * @param templateName the value for md_templates.template_name
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.member_id
     *
     * @return the value of md_templates.member_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.member_id
     *
     * @param memberId the value for md_templates.member_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.book_id
     *
     * @return the value of md_templates.book_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.book_id
     *
     * @param bookId the value for md_templates.book_id
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.is_global
     *
     * @return the value of md_templates.is_global
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getIsGlobal() {
        return isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.is_global
     *
     * @param isGlobal the value for md_templates.is_global
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setIsGlobal(Integer isGlobal) {
        this.isGlobal = isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.create_time
     *
     * @return the value of md_templates.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.create_time
     *
     * @param createTime the value for md_templates.create_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.modify_time
     *
     * @return the value of md_templates.modify_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.modify_time
     *
     * @param modifyTime the value for md_templates.modify_time
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.modify_at
     *
     * @return the value of md_templates.modify_at
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Integer getModifyAt() {
        return modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.modify_at
     *
     * @param modifyAt the value for md_templates.modify_at
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setModifyAt(Integer modifyAt) {
        this.modifyAt = modifyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.version
     *
     * @return the value of md_templates.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.version
     *
     * @param version the value for md_templates.version
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column md_templates.template_content
     *
     * @return the value of md_templates.template_content
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column md_templates.template_content
     *
     * @param templateContent the value for md_templates.template_content
     *
     * @mbg.generated Tue May 07 23:33:41 CST 2019
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }
}